language: node_js

node_js:
  - "8"
  - "9"
  - "10"

before_install:
  - npm install run-rs -g
  - run-rs -v 4.0.0 &
  - npm install mongoose

install:
  - npm install

script:
  - sleep 15
  - npm test
